basePath: /
definitions:
  models.Classification:
    properties:
      competitionId:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  models.ClassificationWithCompetition:
    properties:
      competition:
        $ref: '#/definitions/models.Competition'
        type: object
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  models.Competition:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  models.OlympicSchedule:
    properties:
      begin:
        type: string
      classification:
        $ref: '#/definitions/models.Classification'
        type: object
      competition:
        $ref: '#/definitions/models.Competition'
        type: object
      content:
        type: string
      createdAt:
        type: string
      end:
        type: string
      id:
        type: integer
      place:
        $ref: '#/definitions/models.Place'
        type: object
      title:
        type: string
      updatedAt:
        type: string
    type: object
  models.Place:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
host: tokyo2020sched.herokuapp.com
info:
  contact: {}
  description: TOKYO2020 schedule API
  license: {}
  title: TOKYO2020 schedule API
  version: "0.1"
paths:
  /classifications:
    get:
      description: 種別等の一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ClassificationWithCompetition'
            type: array
      summary: 種別等一覧を取得
      tags:
      - Classifications
  /classifications/{id}:
    get:
      description: 指定した種別等の詳細情報を取得する
      parameters:
      - description: 種別等ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ClassificationWithCompetition'
            type: object
      summary: 種別等の詳細情報を取得
      tags:
      - Classifications
  /competitions:
    get:
      description: 競技の一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Competition'
            type: array
      summary: 競技一覧を取得
      tags:
      - Competitions
  /competitions/{id}:
    get:
      description: 指定した競技の詳細情報を取得する
      parameters:
      - description: 競技ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Competition'
            type: object
      summary: 競技の詳細情報を取得
      tags:
      - Competitions
  /ping:
    get:
      description: 疎通を確認する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 疎通確認
      tags:
      - Ping
  /places:
    get:
      description: 場所の一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Place'
            type: array
      summary: 場所一覧を取得
      tags:
      - Places
  /places/{id}:
    get:
      description: 指定した場所の詳細情報を取得する
      parameters:
      - description: 場所ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Place'
            type: object
      summary: 場所の詳細情報を取得
      tags:
      - Places
  /schedules/olympic:
    get:
      description: スケジュールの一覧を取得する
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.OlympicSchedule'
            type: array
      summary: スケジュール一覧を取得
      tags:
      - OlympicSchedules
  /schedules/olympic/{id}:
    get:
      description: 指定したスケジュールの詳細情報を取得する
      parameters:
      - description: スケジュールID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.OlympicSchedule'
            type: object
      summary: スケジュールの詳細情報を取得
      tags:
      - OlympicSchedules
schemes:
- https
swagger: "2.0"
